'use strict';function E(d,a,b,c){d.C.Wc(d.Fb,a,b,c,void 0)}function I(d,a,b,c){d.C.ta?E(d,a,b,c):d.C.kg()._OnMessageFromDOM({type:"event",component:d.Fb,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function J(d,a,b){d.C.J(d.Fb,a,b)}function K(d,a){for(const [b,c]of a)J(d,b,c)}function L(d){d.yc||(d.C.Vf(d.Pe),d.yc=!0)}window.cb=class{constructor(d,a){this.C=d;this.Fb=a;this.yc=!1;this.Pe=()=>this.gb()}Sd(){}gb(){}};function M(d){-1!==d.ub&&(self.clearTimeout(d.ub),d.ub=-1)}
window.Ef=class{constructor(d,a){this.yd=d;this.xh=a;this.ub=-1;this.zc=-Infinity;this.Qe=()=>{this.ub=-1;this.zc=Date.now();this.Lb=!0;this.yd();this.Lb=!1};this.ye=this.Lb=!1}Yc(){this.Lb||(M(this),this.zc=Date.now())}c(){M(this);this.Qe=this.yd=null}};"use strict";function N(d,a){J(d,"get-element",b=>{const c=d.ra.get(b.elementId);return a(c,b)})}
window.ai=class extends self.cb{constructor(d,a){super(d,a);this.ra=new Map;this.xd=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const c=this.ra.get(b);this.xd&&c.parentElement.removeChild(c);this.ra.delete(b)}}],["set-visible",b=>{this.xd&&(this.ra.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.xd){var c=this.ra.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=
b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{this.ra.get(b.elementId);throw Error("required override");}],["focus",b=>this.rd(b)],["set-css-style",b=>{this.ra.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ra.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ra.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}rd(d){var a=this.ra.get(d.elementId);d.focus?a.focus():a.blur()}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const e=document.createElement("script");e.async=!1;e.type="module";return m.Lh?new Promise(n=>{const t="c3_resolve_"+a;++a;self[t]=n;e.textContent=m.Uh+`\n\nself["${t}"]();`;document.head.appendChild(e)}):new Promise((n,t)=>{e.onload=n;e.onerror=t;e.src=m;document.head.appendChild(e)})}let c=!1,l=!1;function r(){if(!c){try{new Worker("blob://",{get type(){l=!0}})}catch(m){}c=!0}return l}let p=
new Audio;const f={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function k(m){m=await g(m);return(new TextDecoder("utf-8")).decode(m)}function g(m){return new Promise((e,
n)=>{const t=new FileReader;t.onload=v=>e(v.target.result);t.onerror=v=>n(v);t.readAsArrayBuffer(m)})}const q=[];let y=0;window.RealFile=window.File;const u=[],w=new Map,x=new Map;let A=0;const B=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");B.push(m)};const F=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Ia=class m{constructor(e){this.ta=e.Xh;this.Ma=null;this.L="";this.Kc=e.Sh;this.$b={};this.nb=this.Zb=null;
this.wc=[];this.Ob=this.R=this.sb=null;this.rb=-1;this.Dh=()=>this.Hg();this.qb=[];this.v=e.Re;this.Mb="file"===location.protocol.substr(0,4);!this.ta||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&r()||(this.ta=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ta=!1;if("cordova"===this.v&&this.ta)if(/android/i.test(navigator.userAgent)){const n=/Chrome\/(\d+)/i.exec(navigator.userAgent);n&&90<=parseInt(n[1],10)||(this.ta=!1)}else this.ta=!1;this.Ac=this.Ba=null;"html5"!==
this.v&&"playable-ad"!==this.v||!this.Mb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.J("runtime","cordova-fetch-local-file",n=>this.rg(n));this.J("runtime",
"create-job-worker",()=>this.sg());"cordova"===this.v?document.addEventListener("deviceready",()=>this.le(e)):this.le(e)}c(){this.ed();this.Ma&&(this.Ma=this.Ma.onmessage=null);this.Zb&&(this.Zb.terminate(),this.Zb=null);this.nb&&(this.nb.c(),this.nb=null);this.R&&(this.R.parentElement.removeChild(this.R),this.R=null)}zf(){return d&&"cordova"===this.v}Vc(){const e=navigator.userAgent;return d&&F.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(e)}async le(e){"macos-wkwebview"===
this.v&&this.vd({type:"ready"});if("playable-ad"===this.v){this.Ba=self.c3_base64files;this.Ac={};await this.ag();for(let t=0,v=e.vb.length;t<v;++t){var n=e.vb[t].toLowerCase();this.Ac.hasOwnProperty(n)?e.vb[t]={Lh:!0,Uh:this.Ac[n]}:this.Ba.hasOwnProperty(n)&&(e.vb[t]=URL.createObjectURL(this.Ba[n]))}}e.Eh?this.L=e.Eh:(n=location.origin,this.L=("null"===n?"file:///":n)+location.pathname,n=this.L.lastIndexOf("/"),-1!==n&&(this.L=this.L.substr(0,n+1)));e.Zh&&(this.$b=e.Zh);n=new MessageChannel;this.Ma=
n.port1;this.Ma.onmessage=t=>this._OnMessageFromRuntime(t.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(t=>this.Dg(t));this.Ob=new self.Af(this);await O(this.Ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ta?await this.mg(e,n.port2):await this.lg(e,n.port2)}hd(e){e=this.$b.hasOwnProperty(e)?this.$b[e]:e.endsWith("/workermain.js")&&this.$b.hasOwnProperty("workermain.js")?
this.$b["workermain.js"]:"playable-ad"===this.v&&this.Ba.hasOwnProperty(e.toLowerCase())?this.Ba[e.toLowerCase()]:e;e instanceof Blob&&(e=URL.createObjectURL(e));return e}async Pc(e,n,t){if(e.startsWith("blob:"))return new Worker(e,t);if("cordova"===this.v&&this.Mb)return e=await this.ac(t.Kh?e:this.Kc+e),new Worker(URL.createObjectURL(new Blob([e],{type:"application/javascript"})),t);e=new URL(e,n);if(location.origin!==e.origin){e=await fetch(e);if(!e.ok)throw Error("failed to fetch worker script");
e=await e.blob();return new Worker(URL.createObjectURL(e),t)}return new Worker(e,t)}Va(){return Math.max(window.innerWidth,1)}Ua(){return Math.max(window.innerHeight,1)}ke(e){var n=this.Ob;return{baseUrl:this.L,windowInnerWidth:this.Va(),windowInnerHeight:this.Ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.zb(),projectData:e.mi,previewImageBlobs:window.cr_previewImageBlobs||this.Ba,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.hi||"",exportType:e.Re,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.li,jobScheduler:{inputPort:n.Fd,outputPort:n.Ld,maxNumWorkers:n.zh},supportedAudioFormats:f,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Kc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Kc+"opus.wasm.wasm",isFileProtocol:this.Mb,isiOSCordova:this.zf(),isiOSWebView:this.Vc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async mg(e,n){var t=this.hd(e.Yh);this.Zb=
await this.Pc(t,this.L,{type:"module",name:"Runtime",Kh:!0});this.R=document.createElement("canvas");this.R.style.display="none";t=this.R.transferControlToOffscreen();document.body.appendChild(this.R);window.c3canvas=this.R;let v=e.Rd||[],D=e.vb;v=await Promise.all(v.map(z=>this.hb(z)));D=await Promise.all(D.map(z=>this.hb(z)));if("cordova"===this.v)for(let z=0,C=e.Nc.length;z<C;++z){const G=e.Nc[z],H=G[0];if(H===e.Pd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))G[1]=await this.hb(H)}this.Zb.postMessage(Object.assign(this.ke(e),
{type:"init-runtime",isInWorker:!0,messagePort:n,canvas:t,workerDependencyScripts:v,engineScripts:D,projectScripts:e.Nc,mainProjectScript:e.Pd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[n,t,...P(this.Ob)]);this.wc=u.map(z=>new z(this));this.je();self.c3_callFunction=(z,C)=>this.sb.ng(z,C);"preview"===this.v&&(self.goToLastErrorScript=()=>this.Wc("runtime","go-to-last-error-script"))}async lg(e,n){this.R=document.createElement("canvas");this.R.style.display="none";document.body.appendChild(this.R);
window.c3canvas=this.R;this.wc=u.map(z=>new z(this));this.je();var t=e.vb.map(z=>"string"===typeof z?(new URL(z,this.L)).toString():z);Array.isArray(e.Rd)&&t.unshift(...e.Rd);t=await Promise.all(t.map(z=>this.hb(z)));await Promise.all(t.map(z=>b(z)));t=self.C3_ProjectScriptsStatus;const v=e.Pd,D=e.Nc;for(let [z,C]of D)if(C||(C=z),z===v)try{C=await this.hb(C),await b(C),"preview"!==this.v||t[z]||this.te(z,"main script did not run to completion")}catch(G){this.te(z,G)}else if("scriptsInEvents.js"===
z||z.endsWith("/scriptsInEvents.js"))C=await this.hb(C),await b(C);"preview"===this.v&&"object"!==typeof self.$h.bi?(this.pc(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(e=Object.assign(this.ke(e),{isInWorker:!1,messagePort:n,canvas:this.R,runOnStartupFunctions:B}),this.ne(),this.nb=self.C3_CreateRuntime(e),await self.C3_InitRuntime(this.nb,
e))}te(e,n){this.pc();console.error(`[Preview] Failed to load project main script (${e}): `,n);alert(`Failed to load project main script (${e}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ne(){this.pc()}pc(){const e=window.Fh;e&&(e.parentElement.removeChild(e),window.Fh=null)}async sg(){const e=await Q(this.Ob);return{outputPort:e,transferables:[e]}}kg(){if(this.ta)throw Error("not available in worker mode");return this.nb}Wc(e,n,t,v,D){this.Ma.postMessage({type:"event",
component:e,handler:n,dispatchOpts:v||null,data:t,responseId:null},D)}ae(e,n,t,v,D){const z=A++,C=new Promise((G,H)=>{x.set(z,{resolve:G,reject:H})});this.Ma.postMessage({type:"event",component:e,handler:n,dispatchOpts:v||null,data:t,responseId:z},D);return C}["_OnMessageFromRuntime"](e){const n=e.type;if("event"===n)return this.xg(e);if("result"===n)this.Kg(e);else if("runtime-ready"===n)this.Lg();else if("alert-error"===n)this.pc(),alert(e.message);else if("creating-runtime"===n)this.ne();else throw Error(`unknown message '${n}'`);
}xg(e){const n=e.component,t=e.handler,v=e.data,D=e.responseId;if(e=w.get(n))if(e=e.get(t)){var z=null;try{z=e(v)}catch(C){console.error(`Exception in '${n}' handler '${t}':`,C);null!==D&&this.oc(D,!1,""+C);return}if(null===D)return z;z&&z.then?z.then(C=>this.oc(D,!0,C)).catch(C=>{console.error(`Rejection from '${n}' handler '${t}':`,C);this.oc(D,!1,""+C)}):this.oc(D,!0,z)}else console.warn(`[DOM] No handler '${t}' for component '${n}'`);else console.warn(`[DOM] No event handlers for component '${n}'`)}oc(e,
n,t){let v;t&&t.transferables&&(v=t.transferables);this.Ma.postMessage({type:"result",responseId:e,isOk:n,result:t},v)}Kg(e){const n=e.responseId,t=e.isOk;e=e.result;const v=x.get(n);t?v.resolve(e):v.reject(e);x.delete(n)}J(e,n,t){let v=w.get(e);v||(v=new Map,w.set(e,v));if(v.has(n))throw Error(`[DOM] Component '${e}' already has handler '${n}'`);v.set(n,t)}static wb(e){if(u.includes(e))throw Error("DOM handler already added");u.push(e)}je(){for(const e of this.wc)if("runtime"===e.Fb){this.sb=e;return}throw Error("cannot find runtime DOM handler");
}Dg(e){this.Wc("debugger","message",e)}Lg(){for(const e of this.wc)e.Sd()}static zb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static qc(e){h=!!e}Vf(e){this.qb.push(e);this.ud()}Xg(e){e=this.qb.indexOf(e);if(-1===e)throw Error("invalid callback");this.qb.splice(e,1);this.qb.length||this.ed()}ud(){-1===this.rb&&this.qb.length&&(this.rb=requestAnimationFrame(this.Dh))}ed(){-1!==this.rb&&(cancelAnimationFrame(this.rb),this.rb=-1)}Hg(){this.rb=
-1;for(const e of this.qb)e();this.ud()}Ta(e){this.sb.Ta(e)}fb(e){this.sb.fb(e)}td(){this.sb.td()}jc(e){this.sb.jc(e)}yf(){return!!f["audio/webm; codecs=opus"]}async vh(e){e=await this.ae("runtime","opus-decode",{arrayBuffer:e},null,[e]);return new Float32Array(e)}xf(e){return/^(?:[a-z\-]+:)?\/\//.test(e)||"data:"===e.substr(0,5)||"blob:"===e.substr(0,5)}$d(e){return!this.xf(e)}async hb(e){return"cordova"===this.v&&(e.startsWith("file:")||this.Mb&&this.$d(e))?(e.startsWith(this.L)&&(e=e.substr(this.L.length)),
e=await this.ac(e),URL.createObjectURL(new Blob([e],{type:"application/javascript"}))):e}async rg(e){const n=e.filename;switch(e.as){case "text":return await this.nf(n);case "buffer":return await this.ac(n);default:throw Error("unsupported type");}}Wd(e){const n=window.cordova.file.applicationDirectory+"www/"+e.toLowerCase();return new Promise((t,v)=>{window.resolveLocalFileSystemURL(n,D=>{D.file(t,v)},v)})}async nf(e){e=await this.Wd(e);return await k(e)}fd(){if(q.length&&!(8<=y)){y++;var e=q.shift();
this.bg(e.filename,e.Vh,e.Ih)}}ac(e){return new Promise((n,t)=>{q.push({filename:e,Vh:v=>{y--;this.fd();n(v)},Ih:v=>{y--;this.fd();t(v)}});this.fd()})}async bg(e,n,t){try{const v=await this.Wd(e),D=await g(v);n(D)}catch(v){t(v)}}vd(e){if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(e));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(e));else throw Error("cannot send wrapper message");}async ag(){const e=[];for(const [n,
t]of Object.entries(this.Ba))e.push(this.$f(n,t));await Promise.all(e)}async $f(e,n){if("object"===typeof n)this.Ba[e]=new Blob([n.str],{type:n.type}),this.Ac[e]=n.str;else{let t=await this.ig(n);t||(t=this.dg(n));this.Ba[e]=t}}async ig(e){try{return await (await fetch(e)).blob()}catch(n){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
n),null}}dg(e){e=this.Rg(e);return this.Yf(e.data,e.Mh)}Rg(e){var n=e.indexOf(",");if(0>n)throw new URIError("expected comma in data: uri");var t=e.substring(n+1);n=e.substring(5,n).split(";");e=n[0]||"";const v=n[2];t="base64"===n[1]||"base64"===v?atob(t):decodeURIComponent(t);return{Mh:e,data:t}}Yf(e,n){var t=e.length;let v=t>>2,D=new Uint8Array(t),z=new Uint32Array(D.buffer,0,v),C,G;for(G=C=0;C<v;++C)z[C]=e.charCodeAt(G++)|e.charCodeAt(G++)<<8|e.charCodeAt(G++)<<16|e.charCodeAt(G++)<<24;for(t&=
3;t--;)D[G]=e.charCodeAt(G),++G;return new Blob([D],{type:n})}}}"use strict";
{const d=self.Ia;function a(h){return h.sourceCapabilities&&h.sourceCapabilities.firesTouchEvents||h.originalEvent&&h.originalEvent.sourceCapabilities&&h.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},r={dispatchRuntimeEvent:!0};function p(h){return new Promise((m,e)=>{const n=document.createElement("link");n.onload=()=>m(n);n.onerror=t=>e(t);n.rel=
"stylesheet";n.href=h;document.head.appendChild(n)})}function f(h){return new Promise((m,e)=>{const n=new Image;n.onload=()=>m(n);n.onerror=t=>e(t);n.src=h})}async function k(h){h=URL.createObjectURL(h);try{return await f(h)}finally{URL.revokeObjectURL(h)}}function g(h){return new Promise((m,e)=>{let n=new FileReader;n.onload=t=>m(t.target.result);n.onerror=t=>e(t);n.readAsText(h)})}async function q(h,m,e){if(!/firefox/i.test(navigator.userAgent))return await k(h);var n=await g(h);n=(new DOMParser).parseFromString(n,
"image/svg+xml");const t=n.documentElement;if(t.hasAttribute("width")&&t.hasAttribute("height")){const v=t.getAttribute("width"),D=t.getAttribute("height");if(!v.includes("%")&&!D.includes("%"))return await k(h)}t.setAttribute("width",m+"px");t.setAttribute("height",e+"px");n=(new XMLSerializer).serializeToString(n);h=new Blob([n],{type:"image/svg+xml"});return await k(h)}function y(h){do{if(h.parentNode&&h.hasAttribute("contenteditable"))return!0;h=h.parentNode}while(h);return!1}const u=new Set(["input",
"textarea","datalist","select"]),w=new Set(["canvas","body","html"]);function x(h){w.has(h.target.tagName.toLowerCase())&&h.preventDefault()}function A(h){(h.metaKey||h.ctrlKey)&&h.preventDefault()}self.C3_GetSvgImageSize=async function(h){h=await k(h);if(0<h.width&&0<h.height)return[h.width,h.height];{h.style.position="absolute";h.style.left="0px";h.style.top="0px";h.style.visibility="hidden";document.body.appendChild(h);const m=h.getBoundingClientRect();document.body.removeChild(h);return[m.width,
m.height]}};self.C3_RasterSvgImageBlob=async function(h,m,e,n,t){h=await q(h,m,e);const v=document.createElement("canvas");v.width=n;v.height=t;v.getContext("2d").drawImage(h,0,0,m,e);return v};let B=!1;document.addEventListener("pause",()=>B=!0);document.addEventListener("resume",()=>B=!1);function F(){try{return window.parent&&window.parent.document.hasFocus()}catch(h){return!1}}d.wb(class extends self.cb{constructor(h){super(h,"runtime");this.De=!0;this.tb=-1;this.Nd="any";this.ue=this.ve=!1;this.mb=
this.Wb=this.Ya=null;this.Gc=this.Fc=0;h.J("canvas","update-size",n=>this.Og(n));h.J("runtime","invoke-download",n=>this.Bg(n));h.J("runtime","raster-svg-image",n=>this.Ig(n));h.J("runtime","get-svg-image-size",n=>this.zg(n));h.J("runtime","set-target-orientation",n=>this.Mg(n));h.J("runtime","register-sw",()=>this.Jg());h.J("runtime","post-to-debugger",n=>this.pe(n));h.J("runtime","go-to-script",n=>this.pe(n));h.J("runtime","before-start-ticking",()=>this.qg());h.J("runtime","debug-highlight",n=>
this.tg(n));h.J("runtime","enable-device-orientation",()=>this.Xf());h.J("runtime","enable-device-motion",()=>this.Wf());h.J("runtime","add-stylesheet",n=>this.pg(n));h.J("runtime","alert",n=>this.md(n));h.J("runtime","hide-cordova-splash",()=>this.Ag());const m=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",n=>{const t=n.target;m.has(t.tagName.toLowerCase())||y(t)||n.preventDefault()});const e=h.R;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",
x);e.addEventListener("selectstart",x);e.addEventListener("gesturehold",x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),e.addEventListener("pointerdown",x)):e.addEventListener("touchstart",x);this.Tb=0;window.addEventListener("mousedown",n=>{1===n.button&&n.preventDefault()});window.addEventListener("mousewheel",A,{passive:!1});window.addEventListener("wheel",A,{passive:!1});window.addEventListener("resize",
()=>this.Pg());window.addEventListener("fullscreenchange",()=>this.Bb());window.addEventListener("webkitfullscreenchange",()=>this.Bb());window.addEventListener("mozfullscreenchange",()=>this.Bb());window.addEventListener("fullscreenerror",n=>this.od(n));window.addEventListener("webkitfullscreenerror",n=>this.od(n));window.addEventListener("mozfullscreenerror",n=>this.od(n));h.Vc()&&window.addEventListener("focusout",()=>{{const v=document.activeElement;if(v){var n=v.tagName.toLowerCase();var t=new Set("email number password search tel text url".split(" "));
n="textarea"===n?!0:"input"===n?t.has(v.type.toLowerCase()||"text"):y(v)}else n=!1}n||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=n=>this.Qg(n);this.ob=new Set;this.Bc=new WeakSet;this.La=!1}qg(){"cordova"===this.C.v?(document.addEventListener("pause",()=>this.sd(!0)),document.addEventListener("resume",()=>this.sd(!1))):document.addEventListener("visibilitychange",()=>this.sd(document.hidden));return{isSuspended:!(!document.hidden&&!B)}}Sd(){window.addEventListener("focus",()=>
this.Db("window-focus"));window.addEventListener("blur",()=>{this.Db("window-blur",{parentHasFocus:F()});this.Tb=0});window.addEventListener("focusin",m=>{m=m.target;(u.has(m.tagName.toLowerCase())||y(m))&&this.Db("keyboard-blur")});window.addEventListener("keydown",m=>this.oe("keydown",m));window.addEventListener("keyup",m=>this.oe("keyup",m));window.addEventListener("dblclick",m=>this.pd("dblclick",m,c));window.addEventListener("wheel",m=>this.Fg(m));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
m=>{this.jd(m);this.Cb("pointerdown",m)}),this.C.ta&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Wb=new self.Ef(()=>this.gg(),5),this.Wb.ye=!0,window.addEventListener("pointerrawupdate",m=>this.Gg(m))):window.addEventListener("pointermove",m=>this.Cb("pointermove",m)),window.addEventListener("pointerup",m=>this.Cb("pointerup",m)),window.addEventListener("pointercancel",m=>this.Cb("pointercancel",m))):(window.addEventListener("mousedown",m=>{this.jd(m);this.qd("pointerdown",
m)}),window.addEventListener("mousemove",m=>this.qd("pointermove",m)),window.addEventListener("mouseup",m=>this.qd("pointerup",m)),window.addEventListener("touchstart",m=>{this.jd(m);this.nc("pointerdown",m)}),window.addEventListener("touchmove",m=>this.nc("pointermove",m)),window.addEventListener("touchend",m=>this.nc("pointerup",m)),window.addEventListener("touchcancel",m=>this.nc("pointercancel",m)));const h=()=>this.td();window.addEventListener("pointerup",h,!0);window.addEventListener("touchend",
h,!0);window.addEventListener("click",h,!0);window.addEventListener("keydown",h,!0);window.addEventListener("gamepadconnected",h,!0)}Db(h,m){E(this,h,m||null,r)}Va(){return this.C.Va()}Ua(){return this.C.Ua()}Pg(){const h=this.Va(),m=this.Ua();this.Db("window-resize",{innerWidth:h,innerHeight:m,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.zb()});this.C.Vc()&&(-1!==this.tb&&clearTimeout(this.tb),this.qe(h,m,0))}Yg(h,m,e){-1!==this.tb&&clearTimeout(this.tb);this.tb=setTimeout(()=>this.qe(h,
m,e),48)}qe(h,m,e){const n=this.Va(),t=this.Ua();this.tb=-1;n!=h||t!=m?this.Db("window-resize",{innerWidth:n,innerHeight:t,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.zb()}):10>e&&this.Yg(n,t,e+1)}Mg(h){this.Nd=h.targetOrientation}rh(){const h=this.Nd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(m=>console.warn("[Construct 3] Failed to lock orientation: ",m));else try{let m=!1;screen.lockOrientation?m=screen.lockOrientation(h):screen.webkitLockOrientation?
m=screen.webkitLockOrientation(h):screen.mozLockOrientation?m=screen.mozLockOrientation(h):screen.msLockOrientation&&(m=screen.msLockOrientation(h));m||console.warn("[Construct 3] Failed to lock orientation")}catch(m){console.warn("[Construct 3] Failed to lock orientation: ",m)}}Bb(){const h=d.zb();h&&"any"!==this.Nd&&this.rh();E(this,"fullscreenchange",{isFullscreen:h,innerWidth:this.Va(),innerHeight:this.Ua()})}od(h){console.warn("[Construct 3] Fullscreen request failed: ",h);E(this,"fullscreenerror",
{isFullscreen:d.zb(),innerWidth:this.Va(),innerHeight:this.Ua()})}sd(h){h?this.C.ed():this.C.ud();E(this,"visibilitychange",{hidden:h})}oe(h,m){"Backspace"===m.key&&x(m);const e=b.get(m.code)||m.code;I(this,h,{code:e,key:m.key,which:m.which,repeat:m.repeat,altKey:m.altKey,ctrlKey:m.ctrlKey,metaKey:m.metaKey,shiftKey:m.shiftKey,timeStamp:m.timeStamp},c)}Fg(h){E(this,"wheel",{clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,deltaX:h.deltaX,deltaY:h.deltaY,deltaZ:h.deltaZ,deltaMode:h.deltaMode,
timeStamp:h.timeStamp},c)}pd(h,m,e){a(m)||I(this,h,{button:m.button,buttons:m.buttons,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,movementX:m.movementX||0,movementY:m.movementY||0,timeStamp:m.timeStamp},e)}qd(h,m){if(!a(m)){var e=this.Tb;"pointerdown"===h&&0!==e?h="pointermove":"pointerup"===h&&0!==m.buttons&&(h="pointermove");I(this,h,{pointerId:1,pointerType:"mouse",button:m.button,buttons:m.buttons,lastButtons:e,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,
movementX:m.movementX||0,movementY:m.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:m.timeStamp},c);this.Tb=m.buttons;this.pd(m.type,m,l)}}Cb(h,m){this.Wb&&"pointermove"!==h&&this.Wb.Yc();var e=0;"mouse"===m.pointerType&&(e=this.Tb);I(this,h,{pointerId:m.pointerId,pointerType:m.pointerType,button:m.button,buttons:m.buttons,lastButtons:e,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,movementX:(m.movementX||0)+this.Fc,movementY:(m.movementY||
0)+this.Gc,width:m.width||0,height:m.height||0,pressure:m.pressure||0,tangentialPressure:m.tangentialPressure||0,tiltX:m.tiltX||0,tiltY:m.tiltY||0,twist:m.twist||0,timeStamp:m.timeStamp},c);this.Gc=this.Fc=0;"mouse"===m.pointerType&&(e="mousemove","pointerdown"===h?e="mousedown":"pointerup"===h&&(e="mouseup"),this.pd(e,m,l),this.Tb=m.buttons)}Gg(h){this.mb&&(this.Fc+=this.mb.movementX||0,this.Gc+=this.mb.movementY||0);this.mb=h;h=this.Wb;if(-1===h.ub){var m=Date.now(),e=m-h.zc,n=h.xh;e>=n&&h.ye?(h.zc=
m,h.Lb=!0,h.yd(),h.Lb=!1):h.ub=self.setTimeout(h.Qe,Math.max(n-e,4))}}gg(){this.Cb("pointermove",this.mb);this.mb=null}nc(h,m){for(let e=0,n=m.changedTouches.length;e<n;++e){const t=m.changedTouches[e];I(this,h,{pointerId:t.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:t.clientX,clientY:t.clientY,pageX:t.pageX,pageY:t.pageY,movementX:m.movementX||0,movementY:m.movementY||0,width:2*(t.radiusX||t.webkitRadiusX||0),height:2*(t.radiusY||t.webkitRadiusY||0),pressure:t.force||
t.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:t.rotationAngle||0,timeStamp:m.timeStamp},c)}}jd(h){window!==window.top&&window.focus();this.me(h.target)&&document.activeElement&&!this.me(document.activeElement)&&document.activeElement.blur()}me(h){return!h||h===document||h===window||h===document.body||"canvas"===h.tagName.toLowerCase()}Xf(){this.ve||(this.ve=!0,window.addEventListener("deviceorientation",h=>this.vg(h)),window.addEventListener("deviceorientationabsolute",h=>this.wg(h)))}Wf(){this.ue||
(this.ue=!0,window.addEventListener("devicemotion",h=>this.ug(h)))}vg(h){E(this,"deviceorientation",{absolute:!!h.absolute,alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0,timeStamp:h.timeStamp,webkitCompassHeading:h.webkitCompassHeading,webkitCompassAccuracy:h.webkitCompassAccuracy},c)}wg(h){E(this,"deviceorientationabsolute",{absolute:!!h.absolute,alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0,timeStamp:h.timeStamp},c)}ug(h){let m=null;var e=h.acceleration;e&&(m={x:e.x||0,y:e.y||0,z:e.z||0});
e=null;var n=h.accelerationIncludingGravity;n&&(e={x:n.x||0,y:n.y||0,z:n.z||0});n=null;const t=h.rotationRate;t&&(n={alpha:t.alpha||0,beta:t.beta||0,gamma:t.gamma||0});E(this,"devicemotion",{acceleration:m,accelerationIncludingGravity:e,rotationRate:n,interval:h.interval,timeStamp:h.timeStamp},c)}Og(h){const m=this.C.R;m.style.width=h.styleWidth+"px";m.style.height=h.styleHeight+"px";m.style.marginLeft=h.marginLeft+"px";m.style.marginTop=h.marginTop+"px";this.De&&(m.style.display="",this.De=!1)}Bg(h){const m=
h.url;h=h.filename;const e=document.createElement("a"),n=document.body;e.textContent=h;e.href=m;e.download=h;n.appendChild(e);e.click();n.removeChild(e)}async Ig(h){var m=h.imageBitmapOpts;h=await self.C3_RasterSvgImageBlob(h.blob,h.imageWidth,h.imageHeight,h.surfaceWidth,h.surfaceHeight);m=m?await createImageBitmap(h,m):await createImageBitmap(h);return{imageBitmap:m,transferables:[m]}}async zg(h){return await self.C3_GetSvgImageSize(h.blob)}async pg(h){await p(h.url)}td(){var h=[...this.ob];this.ob.clear();
if(!this.La)for(const m of h)(h=m.play())&&h.catch(()=>{this.Bc.has(m)||this.ob.add(m)})}Ta(h){if("function"!==typeof h.play)throw Error("missing play function");this.Bc.delete(h);let m;try{m=h.play()}catch(e){this.ob.add(h);return}m&&m.catch(()=>{this.Bc.has(h)||this.ob.add(h)})}fb(h){this.ob.delete(h);this.Bc.add(h)}jc(h){this.La=!!h}Ag(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}tg(h){if(h.show){this.Ya||(this.Ya=document.createElement("div"),this.Ya.id=
"inspectOutline",document.body.appendChild(this.Ya));var m=this.Ya;m.style.display="";m.style.left=h.left-1+"px";m.style.top=h.top-1+"px";m.style.width=h.width+2+"px";m.style.height=h.height+2+"px";m.textContent=h.name}else this.Ya&&(this.Ya.style.display="none")}Jg(){window.C3_RegisterSW&&window.C3_RegisterSW()}pe(h){window.c3_postToMessagePort&&(h.from="runtime",window.c3_postToMessagePort(h))}ng(h,m){return this.C.ae(this.Fb,"js-invoke-function",{name:h,params:m},void 0,void 0)}md(h){alert(h.message)}Qg(h){"entered-fullscreen"===
h?(d.qc(!0),this.Bb()):"exited-fullscreen"===h?(d.qc(!1),this.Bb()):console.warn("Unknown wrapper message: ",h)}})}"use strict";async function O(d){if(d.wh)throw Error("already initialised");d.wh=!0;var a=d.Jc.hd("dispatchworker.js");d.Ad=await d.Jc.Pc(a,d.L,{name:"DispatchWorker"});a=new MessageChannel;d.Fd=a.port1;d.Ad.postMessage({type:"_init","in-port":a.port2},[a.port2]);d.Ld=await Q(d)}function P(d){return[d.Fd,d.Ld]}
async function Q(d){const a=d.Ee.length;var b=d.Jc.hd("jobworker.js");b=await d.Jc.Pc(b,d.L,{name:"JobWorker"+a});const c=new MessageChannel,l=new MessageChannel;d.Ad.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":l.port2},[c.port2,l.port2]);d.Ee.push(b);return l.port1}
self.Af=class{constructor(d){this.Jc=d;this.L=d.L;this.L="preview"===d.v?this.L+"workers/":this.L+d.Kc;this.zh=Math.min(navigator.hardwareConcurrency||2,16);this.Ad=null;this.Ee=[];this.Ld=this.Fd=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ia({Xh:!1,Yh:"workermain.js",vb:["scripts/c3runtime.js"],Nc:[],Pd:"",Sh:"scripts/",Rd:[],Re:"html5"}));"use strict";
{const d=180/Math.PI;self.ua=class extends self.cb{constructor(a){super(a,"audio");this.vc=this.f=null;this.xc=this.Ed=!1;this.Oa=()=>this.sh();this.pa=[];this.K=[];this.Aa=null;this.Fe="";this.Ge=-1;this.Vb=new Map;this.Id=1;this.La=!1;this.Od=0;this.Lc=1;this.Bd=0;this.Ie="HRTF";this.ze="inverse";this.Je=600;this.He=1E4;this.Le=1;this.Be=this.Md=!1;this.Oe=this.C.yf();this.qa=new Map;this.jb=new Set;this.Gd=!1;this.Jd="";this.Za=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Eg(b,c);this.uc=null;
self.C3Audio_GetOutputStream=()=>this.yg();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.cg(b)],["play",b=>this.Sg(b)],["stop",b=>this.ph(b)],["stop-all",()=>this.qh()],["set-paused",b=>this.ih(b)],["set-volume",b=>this.nh(b)],["fade-volume",b=>this.hg(b)],["set-master-volume",b=>this.gh(b)],["set-muted",b=>this.hh(b)],["set-silent",b=>this.kh(b)],["set-looping",b=>this.fh(b)],["set-playback-rate",b=>this.jh(b)],["seek",b=>this.Zg(b)],["preload",b=>this.Tg(b)],["unload",b=>
this.th(b)],["unload-all",()=>this.uh()],["set-suspended",b=>this.lh(b)],["add-effect",b=>this.he(b)],["set-effect-param",b=>this.bh(b)],["remove-effects",b=>this.Vg(b)],["tick",b=>this.Ng(b)],["load-state",b=>this.Cg(b)]])}async cg(a){a.isiOSCordova&&(this.Md=!0);this.Od=a.timeScaleMode;this.Ie=["equalpower","HRTF","soundfield"][a.panningModel];this.ze=["linear","inverse","exponential"][a.distanceModel];this.Je=a.refDistance;this.He=a.maxDistance;this.Le=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.Oe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.ie();this.f.onstatechange=()=>{"running"!==this.f.state&&this.ie()};this.vc=this.f.createGain();this.vc.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.Qc();try{await Promise.all(a.preloadList.map(c=>this.lc(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}ie(){this.xc||(this.Ed=!1,window.addEventListener("pointerup",this.Oa,!0),window.addEventListener("touchend",this.Oa,!0),window.addEventListener("click",this.Oa,!0),window.addEventListener("keydown",this.Oa,!0),this.xc=!0)}eg(){this.xc&&(this.Ed=!0,window.removeEventListener("pointerup",this.Oa,!0),window.removeEventListener("touchend",
this.Oa,!0),window.removeEventListener("click",this.Oa,!0),window.removeEventListener("keydown",this.Oa,!0),this.xc=!1)}sh(){if(!this.Ed){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.eg()}}fa(){return this.f}Qc(){return this.f.currentTime}Qa(){return this.vc}Yd(a){return(a=this.qa.get(a.toLowerCase()))?a[0].Z():this.Qa()}Se(a,b){a=a.toLowerCase();let c=this.qa.get(a);
c||(c=[],this.qa.set(a,c));b.eh(c.length);b.mh(a);c.push(b);this.se(a)}se(a){let b=this.Qa();const c=this.qa.get(a);if(c&&c.length){b=c[0].Z();for(let l=0,r=c.length;l<r;++l){const p=c[l];l+1===r?p.ba(this.Qa()):p.ba(c[l+1].Z())}}for(const l of this.Ga(a))l.Ff(b);this.Za&&this.Jd===a&&(this.Za.disconnect(),this.Za.connect(b))}dc(){return this.Id}fc(){return this.La}dh(){this.Be=!0}qf(a,b){return b?this.C.vh(a).then(c=>{const l=this.f.createBuffer(1,c.length,48E3);l.getChannelData(0).set(c);return l}):
new Promise((c,l)=>{this.f.decodeAudioData(a,c,l)})}Ta(a){this.C.Ta(a)}fb(a){this.C.fb(a)}be(a){let b=0;for(let c=0,l=this.K.length;c<l;++c){const r=this.K[c];this.K[b]=r;r.V===a?r.c():++b}this.K.length=b}Gf(){let a=0;for(let b=0,c=this.pa.length;b<c;++b){const l=this.pa[b];this.pa[a]=l;l.Ra()?l.c():++a}this.pa.length=a}*Ga(a){if(a)for(const b of this.K)self.ua.rf(b.na,a)&&(yield b);else this.Aa&&!this.Aa.ca()&&(yield this.Aa)}async lc(a,b,c,l,r){for(const p of this.pa)if(p.yb()===b)return await p.ha(),
p;if(r)return null;l&&(this.Md||this.Be)&&this.Gf();r="audio/webm; codecs=opus"===c&&!this.Oe;l&&r&&this.dh();a=!l||this.Md||r?new self.lf(this,a,b,c,l,r):new self.ff(this,a,b,c,l);this.pa.push(a);await a.ha();return a}async gd(a,b,c,l,r){for(const p of this.K)if(p.yb()===b&&(p.Oc()||r))return p.Mf(l),p;a=await this.lc(a,b,c,r);l="html5"===a.wd?new self.gf(a.j,a,l):new self.mf(a.j,a,l);this.K.push(l);return l}Uf(a){let b=this.Vb.get(a);if(!b){let c=null;b={Qd:0,Oh:new Promise(l=>c=l),resolve:c};this.Vb.set(a,
b)}b.Qd++}Wg(a){const b=this.Vb.get(a);if(!b)throw Error("expected pending tag");b.Qd--;0===b.Qd&&(b.resolve(),this.Vb.delete(a))}cd(a){a||(a=this.Fe);return(a=this.Vb.get(a))?a.Oh:Promise.resolve()}mc(){if(0<this.jb.size)L(this);else for(const a of this.K)if(a.Zd()){L(this);break}}gb(){for(var a of this.jb)a.gb();a=this.Qc();for(var b of this.K)b.gb(a);b=this.K.filter(c=>c.Zd()).map(c=>c.xb());E(this,"state",{tickCount:this.Ge,audioInstances:b,analysers:[...this.jb].map(c=>c.tf())});0===b.length&&
0===this.jb.size&&this.yc&&(this.C.Xg(this.Pe),this.yc=!1)}Xc(a,b,c){E(this,"trigger",{type:a,tag:b,aiid:c})}async Sg(a){const b=a.originalUrl,c=a.url,l=a.type,r=a.isMusic,p=a.tag,f=a.isLooping,k=a.vol,g=a.pos,q=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Fe=p;this.Uf(p);try{this.Aa=await this.gd(b,c,l,p,r),q?(this.Aa.ic(!0),this.Aa.Lf(q.x,q.y,q.angle,
q.innerAngle,q.outerAngle,q.outerGain),q.hasOwnProperty("uid")&&this.Aa.Nf(q.uid)):this.Aa.ic(!1),this.Aa.Play(f,k,g,y)}catch(u){console.error("[Construct 3] Audio: error starting playback: ",u);return}finally{this.Wg(p)}L(this)}ph(a){a=a.tag;for(const b of this.Ga(a))b.Ka()}qh(){for(const a of this.K)a.Ka()}ih(a){const b=a.tag;a=a.paused;for(const c of this.Ga(b))a?c.Ab():c.hc();this.mc()}nh(a){const b=a.tag;a=a.vol;for(const c of this.Ga(b))c.kc(a)}async hg(a){const b=a.tag,c=a.vol,l=a.duration;
a=a.stopOnEnd;await this.cd(b);for(const r of this.Ga(b))r.sf(c,l,a);this.mc()}gh(a){this.Id=a.vol;for(const b of this.K)b.sc()}hh(a){const b=a.tag;a=a.isMuted;for(const c of this.Ga(b))c.de(a)}kh(a){this.La=a.isSilent;this.C.jc(this.La);for(const b of this.K)b.rc()}fh(a){const b=a.tag;a=a.isLooping;for(const c of this.Ga(b))c.$c(a)}async jh(a){const b=a.tag;a=a.rate;await this.cd(b);for(const c of this.Ga(b))c.fe(a)}async Zg(a){const b=a.tag;a=a.pos;await this.cd(b);for(const c of this.Ga(b))c.Zc(a)}async Tg(a){const b=
a.originalUrl,c=a.url,l=a.type;a=a.isMusic;try{await this.gd(b,c,l,"",a)}catch(r){console.error("[Construct 3] Audio: error preloading: ",r)}}async th(a){if(a=await this.lc("",a.url,a.type,a.isMusic,!0))a.c(),a=this.pa.indexOf(a),-1!==a&&this.pa.splice(a,1)}uh(){for(const a of this.pa)a.c();this.pa.length=0}lh(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.K)b.ad(a);a&&this.f.suspend&&this.f.suspend()}Ng(a){this.Lc=a.timeScale;this.Bd=a.gameTime;this.Ge=a.tickCount;if(0!==
this.Od)for(var b of this.K)b.ib();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const l of this.K)l.za===a&&l.ee(c.x,c.y,c.angle)}}async he(a){var b=a.type;const c=a.tag;var l=a.params;if("filter"===b)l=new self.Ye(this,...l);else if("delay"===b)l=new self.We(this,...l);else if("convolution"===b){b=null;try{b=await this.lc(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(r){console.log("[Construct 3] Audio: error loading convolution: ",
r);return}l=new self.Ve(this,b.oa,...l);l.$g(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)l=new self.Ze(this,...l);else if("phaser"===b)l=new self.af(this,...l);else if("gain"===b)l=new self.$e(this,...l);else if("tremolo"===b)l=new self.cf(this,...l);else if("ringmod"===b)l=new self.bf(this,...l);else if("distortion"===b)l=new self.Xe(this,...l);else if("compressor"===b)l=new self.Ue(this,...l);else if("analyser"===b)l=new self.Te(this,...l);else throw Error("invalid effect type");this.Se(c,
l);this.re()}bh(a){const b=a.index,c=a.param,l=a.value,r=a.ramp,p=a.time;a=this.qa.get(a.tag);!a||0>b||b>=a.length||(a[b].ka(c,l,r,p),this.re())}Vg(a){a=a.tag.toLowerCase();const b=this.qa.get(a);if(b&&b.length){for(const c of b)c.c();this.qa.delete(a);this.se(a)}}Tf(a){this.jb.add(a);this.mc()}Ug(a){this.jb.delete(a)}re(){this.Gd||(this.Gd=!0,Promise.resolve().then(()=>this.fg()))}fg(){const a={};for(const [b,c]of this.qa)a[b]=c.map(l=>l.xb());E(this,"fxstate",{fxstate:a});this.Gd=!1}async Cg(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.K)c.Ra()&&1===b||(c.Ra()||2!==b)&&c.Ka();for(const l of this.qa.values())for(const r of l)r.c();this.qa.clear();this.Lc=a.timeScale;this.Bd=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.La=a.isSilent;this.C.jc(this.La);this.Id=a.masterVolume;c=[];for(const l of Object.values(a.effects))c.push(Promise.all(l.map(r=>this.he(r))));await Promise.all(c);await Promise.all(a.playing.map(l=>this.og(l,b)));this.mc()}async og(a,b){if(3!==
b){var c=a.bufferOriginalUrl,l=a.bufferUrl,r=a.bufferType,p=a.isMusic,f=a.tag,k=a.isLooping,g=a.volume,q=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.gd(c,l,r,f,p)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Df(a.pan);b.Play(k,g,q,0);a.isPlaying||b.Ab();b.ld(a)}}}Eg(a,b){this.Za&&this.Za.disconnect();this.Jd=b.toLowerCase();this.Za=this.f.createMediaStreamSource(a);this.Za.connect(this.Yd(this.Jd))}yg(){this.uc||(this.uc=this.f.createMediaStreamDestination(),
this.vc.connect(this.uc));return this.uc.stream}static rf(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Sf(a){return a*d}static pf(a){return Math.pow(10,a/20)}static Xd(a){return Math.max(Math.min(self.ua.pf(a),1),0)}static Cf(a){return Math.log(a)/Math.log(10)*20}static Bf(a){return self.ua.Cf(Math.max(Math.min(a,1),0))}static Hh(a,b){return 1-Math.exp(-b*a)}};self.Ia.wb(self.ua)}"use strict";
self.Ud=class{constructor(d,a,b,c,l){this.j=d;this.Bh=a;this.$a=b;this.aa=c;this.yh=l;this.wd="";this.g=null}c(){this.g=this.j=null}kd(){}ha(){this.g||(this.g=this.kd());return this.g}fa(){return this.j.fa()}Sc(){return this.Bh}yb(){return this.$a}Rc(){return this.aa}Ra(){return this.yh}wa(){}};"use strict";
self.ff=class extends self.Ud{constructor(d,a,b,c,l){super(d,a,b,c,l);this.wd="html5";this.P=new Audio;this.P.crossOrigin="anonymous";this.P.autoplay=!1;this.P.preload="auto";this.Pb=this.Qb=null;this.P.addEventListener("canplaythrough",()=>!0);this.Ub=this.fa().createGain();this.Sb=null;this.P.addEventListener("canplay",()=>{this.Qb&&(this.Qb(),this.Pb=this.Qb=null);!this.Sb&&this.P&&(this.Sb=this.fa().createMediaElementSource(this.P),this.Sb.connect(this.Ub))});this.onended=null;this.P.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.P.addEventListener("error",r=>{console.error(`[Construct 3] Audio '${this.$a}' error: `,r);this.Pb&&(this.Pb(r),this.Pb=this.Qb=null)})}c(){this.j.be(this);this.Ub.disconnect();this.Ub=null;this.Sb.disconnect();this.Sb=null;this.P&&!this.P.paused&&this.P.pause();this.P=this.onended=null;super.c()}kd(){return new Promise((d,a)=>{this.Qb=d;this.Pb=a;this.P.src=this.$a})}Y(){return this.P}wa(){return this.P.duration}};"use strict";
async function R(d){if(d.Xa)return d.Xa;var a=d.j.C;if("cordova"===a.v&&a.$d(d.$a)&&a.Mb)d.Xa=await a.ac(d.$a);else{a=await fetch(d.$a);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);d.Xa=await a.arrayBuffer()}}async function S(d){if(d.oa)return d.oa;d.oa=await d.j.qf(d.Xa,d.Ah);d.Xa=null}
self.lf=class extends self.Ud{constructor(d,a,b,c,l,r){super(d,a,b,c,l);this.wd="webaudio";this.oa=this.Xa=null;this.Ah=!!r}c(){this.j.be(this);this.oa=this.Xa=null;super.c()}async kd(){try{await R(this),await S(this)}catch(d){console.error(`[Construct 3] Failed to load audio '${this.$a}': `,d)}}wa(){return this.oa?this.oa.duration:0}};"use strict";
{let d=0;self.Vd=class{constructor(a,b,c){this.j=a;this.V=b;this.na=c;this.tc=d++;this.W=this.fa().createGain();this.W.connect(this.Qa());this.G=null;this.Nb=!1;this.Da=[0,0,0];this.Ca=[0,0,0];this.N=!0;this.ea=this.Ea=this.M=!1;this.Yb=1;this.lb=!1;this.Na=1;a=this.j.Od;this.Hd=1===a&&!this.Ra()||2===a;this.Jb=this.za=-1;this.Ne=!1}c(){this.V=this.j=null;this.G&&(this.G.disconnect(),this.G=null);this.W.disconnect();this.W=null}fa(){return this.j.fa()}Qa(){return this.j.Yd(this.na)}dc(){return this.j.dc()}cc(){return this.Hd?
this.j.Bd:performance.now()/1E3}Sc(){return this.V.Sc()}yb(){return this.V.yb()}Rc(){return this.V.Rc()}Ra(){return this.V.Ra()}Mf(a){this.na=a}ca(){}Oc(){}IsPlaying(){return!this.N&&!this.M&&!this.ca()}Zd(){return!this.N&&!this.ca()}eb(){}wa(){return this.V.wa()}Play(){}Ka(){}Ab(){}hc(){}kc(a){this.Yb=a;this.W.gain.cancelScheduledValues(0);this.Jb=-1;this.W.gain.value=this.Tc()}sf(a,b,c){if(!this.lb){a*=this.dc();var l=this.W.gain;l.cancelScheduledValues(0);var r=this.j.Qc();b=r+b;l.setValueAtTime(l.value,
r);l.linearRampToValueAtTime(a,b);this.Yb=a;this.Jb=b;this.Ne=c}}sc(){this.kc(this.Yb)}gb(a){-1!==this.Jb&&a>=this.Jb&&(this.Jb=-1,this.Ne&&this.Ka(),this.j.Xc("fade-ended",this.na,this.tc))}Tc(){const a=this.Yb*this.dc();return isFinite(a)?a:0}de(a){a=!!a;this.lb!==a&&(this.lb=a,this.rc())}fc(){return this.j.fc()}rc(){}$c(){}fe(a){this.Na!==a&&(this.Na=a,this.ib())}ib(){}Zc(){}ad(){}ic(a){a=!!a;this.Nb!==a&&((this.Nb=a)?(this.G||(this.G=this.fa().createPanner(),this.G.panningModel=this.j.Ie,this.G.distanceModel=
this.j.ze,this.G.refDistance=this.j.Je,this.G.maxDistance=this.j.He,this.G.rolloffFactor=this.j.Le),this.W.disconnect(),this.W.connect(this.G),this.G.connect(this.Qa())):(this.G.disconnect(),this.W.disconnect(),this.W.connect(this.Qa())))}Lf(a,b,c,l,r,p){this.Nb&&(this.ee(a,b,c),a=self.ua.Sf,this.G.coneInnerAngle=a(l),this.G.coneOuterAngle=a(r),this.G.coneOuterGain=p)}ee(a,b,c){this.Nb&&(this.Da[0]=a,this.Da[1]=b,this.Da[2]=0,this.Ca[0]=Math.cos(c),this.Ca[1]=Math.sin(c),this.Ca[2]=0,this.G.setPosition(...this.Da),
this.G.setOrientation(...this.Ca))}Nf(a){this.za=a}Uc(){}Ff(a){const b=this.G||this.W;b.disconnect();b.connect(a)}xb(){return{aiid:this.tc,tag:this.na,duration:this.wa(),volume:this.Yb,isPlaying:this.IsPlaying(),playbackTime:this.eb(),playbackRate:this.Na,uid:this.za,bufferOriginalUrl:this.Sc(),bufferUrl:"",bufferType:this.Rc(),isMusic:this.Ra(),isLooping:this.ea,isMuted:this.lb,resumePosition:this.Uc(),pan:this.uf()}}ld(a){this.fe(a.playbackRate);this.de(a.isMuted)}uf(){if(!this.G)return null;const a=
this.G;return{pos:this.Da,orient:this.Ca,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.za}}Df(a){if(a){this.ic(!0);a=this.G;var b=a.pos;this.Da[0]=b[0];this.Da[1]=b[1];this.Da[2]=b[2];b=a.orient;this.Ca[0]=b[0];this.Ca[1]=b[1];this.Ca[2]=b[2];a.setPosition(...this.Da);a.setOrientation(...this.Ca);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.za=a.uid}else this.ic(!1)}}}"use strict";
self.gf=class extends self.Vd{constructor(d,a,b){super(d,a,b);this.V.Ub.connect(this.W);this.V.onended=()=>this.nd()}c(){this.Ka();this.V.Ub.disconnect();super.c()}Y(){return this.V.Y()}nd(){this.N=!0;this.za=-1;this.j.Xc("ended",this.na,this.tc)}ca(){return this.Y().ended}Oc(){return this.N?!0:this.ca()}eb(){let d=this.Y().currentTime;this.ea||(d=Math.min(d,this.wa()));return d}Play(d,a,b){const c=this.Y();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==d&&(c.loop=d);this.kc(a);c.muted&&(c.muted=
!1);if(c.currentTime!==b)try{c.currentTime=b}catch(l){console.warn(`[Construct 3] Exception seeking audio '${this.V.yb()}' to position '${b}': `,l)}this.j.Ta(c);this.M=this.N=!1;this.ea=d;this.Na=1}Ka(){const d=this.Y();d.paused||d.pause();this.j.fb(d);this.N=!0;this.M=!1;this.za=-1}Ab(){if(!(this.M||this.N||this.ca())){var d=this.Y();d.paused||d.pause();this.j.fb(d);this.M=!0}}hc(){!this.M||this.N||this.ca()||(this.j.Ta(this.Y()),this.M=!1)}rc(){this.Y().muted=this.lb||this.fc()}$c(d){d=!!d;this.ea!==
d&&(this.ea=d,this.Y().loop=d)}ib(){let d=this.Na;this.Hd&&(d*=this.j.Lc);try{this.Y().playbackRate=d}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${d}':`,a)}}Zc(d){if(!this.N&&!this.ca())try{this.Y().currentTime=d}catch(a){console.warn(`[Construct 3] Error seeking audio to '${d}': `,a)}}Uc(){return this.eb()}ad(d){d?this.IsPlaying()?(this.Y().pause(),this.Ea=!0):this.Ea=!1:this.Ea&&(this.j.Ta(this.Y()),this.Ea=!1)}};"use strict";
function T(d){d.l&&d.l.disconnect();d.l=null;d.Eb=null}
self.mf=class extends self.Vd{constructor(d,a,b){super(d,a,b);this.l=null;this.Cc=c=>this.nd(c);this.Dd=!0;this.Eb=null;this.X=this.Dc=this.Ec=0;this.Kd=1}c(){this.Ka();T(this);this.Cc=null;super.c()}nd(d){this.M||this.Ea||d.target!==this.Eb||(this.N=this.Dd=!0,this.za=-1,T(this),this.j.Xc("ended",this.na,this.tc))}ca(){return!this.N&&this.l&&this.l.loop||this.M?!1:this.Dd}Oc(){return!this.l||this.N?!0:this.ca()}eb(){let d;d=this.M?this.X:this.Dc+(this.cc()-this.Ec)*this.Na;this.ea||(d=Math.min(d,
this.wa()));return d}Play(d,a,b,c){this.Kd=1;this.kc(a);T(this);this.l=this.fa().createBufferSource();this.l.buffer=this.V.oa;this.l.connect(this.W);this.Eb=this.l;this.l.onended=this.Cc;this.l.loop=d;this.l.start(c,b);this.M=this.N=this.Dd=!1;this.ea=d;this.Na=1;this.Ec=this.cc();this.Dc=b}Ka(){if(this.l)try{this.l.stop(0)}catch(d){}this.N=!0;this.M=!1;this.za=-1}Ab(){this.M||this.N||this.ca()||(this.X=this.eb(),this.ea&&(this.X%=this.wa()),this.M=!0,this.l.stop(0))}hc(){!this.M||this.N||this.ca()||
(T(this),this.l=this.fa().createBufferSource(),this.l.buffer=this.V.oa,this.l.connect(this.W),this.Eb=this.l,this.l.onended=this.Cc,this.l.loop=this.ea,this.sc(),this.ib(),this.l.start(0,this.X),this.Ec=this.cc(),this.Dc=this.X,this.M=!1)}Tc(){return super.Tc()*this.Kd}rc(){this.Kd=this.lb||this.fc()?0:1;this.sc()}$c(d){d=!!d;this.ea!==d&&(this.ea=d,this.l&&(this.l.loop=d))}ib(){let d=this.Na;this.Hd&&(d*=this.j.Lc);this.l&&(this.l.playbackRate.value=d)}Zc(d){this.N||this.ca()||(this.M?this.X=d:(this.Ab(),
this.X=d,this.hc()))}Uc(){return this.X}ad(d){d?this.IsPlaying()?(this.Ea=!0,this.X=this.eb(),this.ea&&(this.X%=this.wa()),this.l.stop(0)):this.Ea=!1:this.Ea&&(T(this),this.l=this.fa().createBufferSource(),this.l.buffer=this.V.oa,this.l.connect(this.W),this.Eb=this.l,this.l.onended=this.Cc,this.l.loop=this.ea,this.sc(),this.ib(),this.l.start(0,this.X),this.Ec=this.cc(),this.Dc=this.X,this.Ea=!1)}ld(d){super.ld(d);this.X=d.resumePosition}};"use strict";
{class d{constructor(a){this.j=a;this.f=a.fa();this.Ce=-1;this.aa=this.na="";this.h=null}c(){this.f=null}eh(a){this.Ce=a}mh(a){this.na=a}s(){return this.f.createGain()}Z(){}ba(){}o(a,b,c,l){a.cancelScheduledValues(0);if(0===l)a.value=b;else{var r=this.f.currentTime;l+=r;switch(c){case 0:a.setValueAtTime(b,l);break;case 1:a.setValueAtTime(a.value,r);a.linearRampToValueAtTime(b,l);break;case 2:a.setValueAtTime(a.value,r),a.exponentialRampToValueAtTime(b,l)}}}xb(){return{type:this.aa,tag:this.na,params:this.h}}}
self.Ye=class extends d{constructor(a,b,c,l,r,p,f){super(a);this.aa="filter";this.h=[b,c,l,r,p,f];this.m=this.s();this.b=this.s();this.b.gain.value=f;this.a=this.s();this.a.gain.value=1-f;this.B=this.f.createBiquadFilter();this.B.type=b;this.B.frequency.value=c;this.B.detune.value=l;this.B.Q.value=r;this.B.gain.vlaue=p;this.m.connect(this.B);this.m.connect(this.a);this.B.connect(this.b)}c(){this.m.disconnect();this.B.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ba(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[5]=b;this.o(this.b.gain,b,c,l);this.o(this.a.gain,1-b,c,l);break;case 1:this.h[1]=b;this.o(this.B.frequency,b,c,l);break;case 2:this.h[2]=b;this.o(this.B.detune,b,c,l);break;case 3:this.h[3]=b;this.o(this.B.Q,b,c,l);break;case 4:this.h[4]=b,this.o(this.B.gain,b,c,l)}}};self.We=class extends d{constructor(a,b,c,l){super(a);this.aa="delay";this.h=[b,c,l];this.m=
this.s();this.b=this.s();this.b.gain.value=l;this.a=this.s();this.a.gain.value=1-l;this.Rb=this.s();this.da=this.f.createDelay(b);this.da.delayTime.value=b;this.Ib=this.s();this.Ib.gain.value=c;this.m.connect(this.Rb);this.m.connect(this.a);this.Rb.connect(this.b);this.Rb.connect(this.da);this.da.connect(this.Ib);this.Ib.connect(this.Rb)}c(){this.m.disconnect();this.b.disconnect();this.a.disconnect();this.Rb.disconnect();this.da.disconnect();this.Ib.disconnect();super.c()}ba(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){const r=self.ua.Xd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[2]=b;this.o(this.b.gain,b,c,l);this.o(this.a.gain,1-b,c,l);break;case 4:this.h[1]=r(b);this.o(this.Ib.gain,r(b),c,l);break;case 5:this.h[0]=b,this.o(this.da.delayTime,b,c,l)}}};self.Ve=class extends d{constructor(a,b,c,l){super(a);this.aa="convolution";this.h=[c,l];this.xe=this.we="";this.m=this.s();this.b=this.s();this.b.gain.value=l;this.a=
this.s();this.a.gain.value=1-l;this.Hb=this.f.createConvolver();this.Hb.normalize=c;this.Hb.buffer=b;this.m.connect(this.Hb);this.m.connect(this.a);this.Hb.connect(this.b)}c(){this.m.disconnect();this.Hb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ba(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.h[1]=b,this.o(this.b.gain,b,c,l),this.o(this.a.gain,1-b,c,l)}}$g(a,b){this.we=
a;this.xe=b}xb(){const a=super.xb();a.bufferOriginalUrl=this.we;a.bufferUrl="";a.bufferType=this.xe;return a}};self.Ze=class extends d{constructor(a,b,c,l,r,p){super(a);this.aa="flanger";this.h=[b,c,l,r,p];this.m=this.s();this.a=this.s();this.a.gain.value=1-p/2;this.b=this.s();this.b.gain.value=p/2;this.Kb=this.s();this.Kb.gain.value=r;this.da=this.f.createDelay(b+c);this.da.delayTime.value=b;this.A=this.f.createOscillator();this.A.frequency.value=l;this.O=this.s();this.O.gain.value=c;this.m.connect(this.da);
this.m.connect(this.a);this.da.connect(this.b);this.da.connect(this.Kb);this.Kb.connect(this.da);this.A.connect(this.O);this.O.connect(this.da.delayTime);this.A.start(0)}c(){this.A.stop(0);this.m.disconnect();this.da.disconnect();this.A.disconnect();this.O.disconnect();this.a.disconnect();this.b.disconnect();this.Kb.disconnect();super.c()}ba(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);
this.h[4]=b;this.o(this.b.gain,b/2,c,l);this.o(this.a.gain,1-b/2,c,l);break;case 6:this.h[1]=b/1E3;this.o(this.O.gain,b/1E3,c,l);break;case 7:this.h[2]=b;this.o(this.A.frequency,b,c,l);break;case 8:this.h[3]=b/100,this.o(this.Kb.gain,b/100,c,l)}}};self.af=class extends d{constructor(a,b,c,l,r,p,f){super(a);this.aa="phaser";this.h=[b,c,l,r,p,f];this.m=this.s();this.a=this.s();this.a.gain.value=1-f/2;this.b=this.s();this.b.gain.value=f/2;this.B=this.f.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=
b;this.B.detune.value=c;this.B.Q.value=l;this.A=this.f.createOscillator();this.A.frequency.value=p;this.O=this.s();this.O.gain.value=r;this.m.connect(this.B);this.m.connect(this.a);this.B.connect(this.b);this.A.connect(this.O);this.O.connect(this.B.frequency);this.A.start(0)}c(){this.A.stop(0);this.m.disconnect();this.B.disconnect();this.A.disconnect();this.O.disconnect();this.a.disconnect();this.b.disconnect();super.c()}ba(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,
b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[5]=b;this.o(this.b.gain,b/2,c,l);this.o(this.a.gain,1-b/2,c,l);break;case 1:this.h[0]=b;this.o(this.B.frequency,b,c,l);break;case 2:this.h[1]=b;this.o(this.B.detune,b,c,l);break;case 3:this.h[2]=b;this.o(this.B.Q,b,c,l);break;case 6:this.h[3]=b;this.o(this.O.gain,b,c,l);break;case 7:this.h[4]=b,this.o(this.A.frequency,b,c,l)}}};self.$e=class extends d{constructor(a,b){super(a);this.aa="gain";this.h=[b];this.i=this.s();this.i.gain.value=
b}c(){this.i.disconnect();super.c()}ba(a){this.i.disconnect();this.i.connect(a)}Z(){return this.i}ka(a,b,c,l){const r=self.ua.Xd;switch(a){case 4:this.h[0]=r(b),this.o(this.i.gain,r(b),c,l)}}};self.cf=class extends d{constructor(a,b,c){super(a);this.aa="tremolo";this.h=[b,c];this.i=this.s();this.i.gain.value=1-c/2;this.A=this.f.createOscillator();this.A.frequency.value=b;this.O=this.s();this.O.gain.value=c/2;this.A.connect(this.O);this.O.connect(this.i.gain);this.A.start(0)}c(){this.A.stop(0);this.A.disconnect();
this.O.disconnect();this.i.disconnect();super.c()}ba(a){this.i.disconnect();this.i.connect(a)}Z(){return this.i}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[1]=b;this.o(this.i.gain,1-b/2,c,l);this.o(this.O.gain,b/2,c,l);break;case 7:this.h[0]=b,this.o(this.A.frequency,b,c,l)}}};self.bf=class extends d{constructor(a,b,c){super(a);this.aa="ringmod";this.h=[b,c];this.m=this.s();this.b=this.s();this.b.gain.value=c;this.a=this.s();this.a.gain.value=1-c;this.Xb=this.s();this.Xb.gain.value=
0;this.A=this.f.createOscillator();this.A.frequency.value=b;this.A.connect(this.Xb.gain);this.A.start(0);this.m.connect(this.Xb);this.m.connect(this.a);this.Xb.connect(this.b)}c(){this.A.stop(0);this.A.disconnect();this.Xb.disconnect();this.m.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ba(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[1]=b;this.o(this.b.gain,b,c,
l);this.o(this.a.gain,1-b,c,l);break;case 7:this.h[0]=b,this.o(this.A.frequency,b,c,l)}}};self.Xe=class extends d{constructor(a,b,c,l,r,p){super(a);this.aa="distortion";this.h=[b,c,l,r,p];this.m=this.s();this.Ic=this.s();this.Hc=this.s();this.ah(l,r);this.b=this.s();this.b.gain.value=p;this.a=this.s();this.a.gain.value=1-p;this.Mc=this.f.createWaveShaper();this.zd=new Float32Array(65536);this.jg(b,c);this.Mc.curve=this.zd;this.m.connect(this.Ic);this.m.connect(this.a);this.Ic.connect(this.Mc);this.Mc.connect(this.Hc);
this.Hc.connect(this.b)}c(){this.m.disconnect();this.Ic.disconnect();this.Mc.disconnect();this.Hc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ah(a,b){.01>a&&(a=.01);this.Ic.gain.value=a;this.Hc.gain.value=Math.pow(1/a,.6)*b}jg(a,b){for(let c=0;32768>c;++c){let l=c/32768;l=this.oh(l,a,b);this.zd[32768+c]=l;this.zd[32768-c-1]=-l}}oh(a,b,c){c=1.05*c*b-b;const l=0>a?-a:a;return(l<b?l:b+c*self.ua.Hh(l-b,1/c))*(0>a?-1:1)}ba(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}Z(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.h[4]=b,this.o(this.b.gain,b,c,l),this.o(this.a.gain,1-b,c,l)}}};self.Ue=class extends d{constructor(a,b,c,l,r,p){super(a);this.aa="compressor";this.h=[b,c,l,r,p];this.i=this.f.createDynamicsCompressor();this.i.threshold.value=b;this.i.knee.value=c;this.i.ratio.value=l;this.i.attack.value=r;this.i.release.value=p}c(){this.i.disconnect();super.c()}ba(a){this.i.disconnect();this.i.connect(a)}Z(){return this.i}ka(){}};
self.Te=class extends d{constructor(a,b,c){super(a);this.aa="analyser";this.h=[b,c];this.i=this.f.createAnalyser();this.i.fftSize=b;this.i.smoothingTimeConstant=c;this.Ae=new Float32Array(this.i.frequencyBinCount);this.Me=new Uint8Array(b);this.Ke=this.pb=0;this.j.Tf(this)}c(){this.j.Ug(this);this.i.disconnect();super.c()}gb(){this.i.getFloatFrequencyData(this.Ae);this.i.getByteTimeDomainData(this.Me);const a=this.i.fftSize;let b=this.pb=0;for(var c=0;c<a;++c){let l=(this.Me[c]-128)/128;0>l&&(l=-l);
this.pb<l&&(this.pb=l);b+=l*l}c=self.ua.Bf;this.pb=c(this.pb);this.Ke=c(Math.sqrt(b/a))}ba(a){this.i.disconnect();this.i.connect(a)}Z(){return this.i}ka(){}tf(){return{tag:this.na,index:this.Ce,peak:this.pb,rms:this.Ke,binCount:this.i.frequencyBinCount,freqBins:this.Ae}}}}"use strict";function U(d){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>E(d,"sw-message",a.data))}
function V(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(d):screen.webkitLockOrientation?a=screen.webkitLockOrientation(d):screen.mozLockOrientation?a=screen.mozLockOrientation(d):screen.msLockOrientation&&(a=screen.msLockOrientation(d));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.Ia.wb(class extends self.cb{constructor(d){super(d,"browser");this.v="";K(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>U(this)],
["alert",a=>this.md(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.rd(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>V(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const c=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.gi||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.v||"macos-wkwebview"===this.v)self.Ia.qc(!0),this.C.vd({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.v||"macos-wkwebview"===this.v?(self.Ia.qc(!1),this.C.vd({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{E(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{E(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{E(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{E(this,"backbutton")})}md(d){alert(d.message)}rd(d){d=d.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;d?a.focus():a.blur()}else d?window.focus():window.blur()}});"use strict";async function W(d,a){a=a.type;let b=!0;0===a?b=await X():1===a&&(b=await Y());E(d,"permission-result",{type:a,result:b})}
async function X(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}
async function Y(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}self.Ia.wb(class extends self.cb{constructor(d){super(d,"touch");J(this,"request-permission",a=>W(this,a))}});"use strict";
{const d={};let a=null,b=null;const c={banner:"ca-app-pub-3940256099942544/2934735716",interstitial:"ca-app-pub-3940256099942544/4411468910",rewarded:"ca-app-pub-3940256099942544/1712485313",rewardedInterstitial:"ca-app-pub-3940256099942544/6978759866"};let l=!1;function r(f,k){d[f]=k;self.admob.configRequest(d)}async function p(){if("android"===self.cordova.platformId)return self.Td(self.device.uuid).toUpperCase();if("ios"===self.cordova.platformId){const f=await self.cordova.plugins.idfa.Jh();if(!f.Wh)return l=
!0,self.Td(f.ki).toUpperCase()}}self.ab={ga:function(f,k){f(null,k)},S:function(f,k){f(k,null)},la:async function(f,k){k="undefined"!==typeof k?k:a.debug;return b?b:b=new Promise(g=>{document.addEventListener("deviceready",async()=>{try{await self.admob.start();if(k){const q=await p();r("testDeviceIds",[q])}g(!0)}catch(q){g(!1),f("Initialization failure",null)}})})},dd:r,Kf:function(f,k,g,q,y,u,w){a||(a={id:f,Ph:k,Nh:g,Th:q,ni:y,debug:u,Gh:w},Object.freeze(a))},vf:function(){return!!a},bc:function(f,
k){if("android"===self.cordova.platformId)return f;if("ios"===self.cordova.platformId){const g=!!c[k];return a.debug&&!l&&g?(console.log("[C3 advert]","USING TEST AD UNITS"),c[k]):f}},get Pa(){return a},get Rf(){return p()}}}"use strict";
{const d=self.ab,a=d.ga,b=d.S,c={get T(){return self.admob.Events.bannerLoad},get U(){return self.admob.Events.bannerLoadFail}};class l{constructor(p,f,k,g){if(!p)return b(g,"Unit ID not specified");if(!f)return b(g,"Ad size not specified");if(!k)return b(g,"Ad position not specified");this.Wa=p;this.Ch=k;this.Fa="";switch(f){case "portrait":this.Fa=5;break;case "landscape":this.Fa=5;break;case "standard":this.Fa=0;break;case "large":this.Fa=1;break;case "medium":this.Fa=2;break;case "full":this.Fa=
3;break;case "leaderboard":this.Fa=4;break;default:this.Fa=5}this.u=null;this.F=this.D=!1}ha(p,f){if(this.u)return a(f,"banner ad loaded");r.call(this,f);p={adUnitId:d.bc(this.Wa,"banner"),size:this.Fa,position:this.Ch,offset:0,npa:"NON_PERSONALIZED"===p?"1":"0"};this.u=new self.admob.BannerAd(p);this.u.load()}async Ja(p){this.u?this.D?b(p,"banner ad still loading"):this.F?a(p,"banner ad already shown"):(await this.u.show(),this.F=!0,a(p,"banner shown")):b(p,"banner ad not created")}async wf(p){this.u?
this.D?b(p,"banner ad still loading"):this.F?(await this.u.hide(),this.F=!1,a(p,"banner ad hidden")):a(p,"banner ad not being shown"):b(p,"banner ad not created")}}function r(p){const f=()=>{this.D=!1;a(p,"banner ad loaded");document.removeEventListener(c.T,f);document.removeEventListener(c.U,k)},k=()=>{this.u=null;this.D=!1;b(p,"banner ad failed to load");document.removeEventListener(c.T,f);document.removeEventListener(c.U,k)};document.addEventListener(c.T,f);document.addEventListener(c.U,k)}self.df=
l}"use strict";
{const d=self.ab,a=d.ga,b=d.S,c={get T(){return self.admob.Events.interstitialLoad},get U(){return self.admob.Events.interstitialLoadFail},get ia(){return self.admob.Events.interstitialShow},get ja(){return self.admob.Events.interstitialShowFail},get va(){return self.admob.Events.interstitialDismiss}};class l{constructor(f,k){if(!f)return b(k,"Unit ID not specified");this.Wa=f;this.u=null;this.I=this.F=this.D=!1;this.$=null;this.g=this.H();document.addEventListener(c.va,async()=>{this.F=!1;this.D=
!0;this.I=!1;this.g=null;this.g=this.H();r.call(this);await this.u.load()})}H(){return this.g?this.g:this.g=new Promise(f=>{this.$=f})}Ha(f){this.I=f;this.$&&this.$(f);this.$=this.g=null;this.g=this.H()}ha(f,k){f={adUnitId:d.bc(this.Wa,"interstitial"),npa:"NON_PERSONALIZED"===f?"1":"0"};this.D=!0;this.I=this.F=!1;this.g=null;this.g=this.H();this.u=new self.admob.InterstitialAd(f);r.call(this,k);this.u.load()}async Ja(f){this.u?this.F?a(f,"interstitial ad already shown"):(this.D&&await this.H(),await (async()=>
{this.I?(p.call(this,f),await this.u.show()):(r.call(this),this.I=!1,this.g=null,this.u.load(),await this.H(),this.I?(p.call(this,f),await this.u.show()):b(f,"interstitial ad failed to load"))})()):b(f,"interstitial ad not created")}}function r(f){const k=()=>{this.D=!1;this.Ha(!0);f&&a(f,"interstitial ad load");document.removeEventListener(c.T,k);document.removeEventListener(c.U,g)},g=()=>{this.D=!1;this.Ha(!1);f&&b(f,"interstitial ad failed to load");document.removeEventListener(c.T,k);document.removeEventListener(c.U,
g)};document.addEventListener(c.T,k);document.addEventListener(c.U,g)}function p(f){const k=()=>{this.F=!0;f&&a(f,"interstitial ad show");document.removeEventListener(c.ia,k);document.removeEventListener(c.ja,g)},g=()=>{this.F=!1;f&&b(f,"interstitial ad failed to show");document.removeEventListener(c.ia,k);document.removeEventListener(c.ja,g)};document.addEventListener(c.ia,k);document.addEventListener(c.ja,g)}self.hf=l}"use strict";
{const d=self.ab,a=d.ga,b=d.S,c={get T(){return self.admob.Events.rewardedLoad},get U(){return self.admob.Events.rewardedLoadFail},get ia(){return self.admob.Events.rewardedShow},get ja(){return self.admob.Events.rewardedShowFail},get va(){return self.admob.Events.rewardedDismiss},get Sa(){return self.admob.Events.rewardedReward}};class l{constructor(f,k){if(!f)return b(k,"Unit ID not specified");this.Wa=f;this.u=null;this.I=this.F=this.D=!1;this.$=null;this.g=this.H();this.ma=null}H(){return this.g?
this.g:this.g=new Promise(f=>{this.$=f})}Ha(f){this.I=f;this.$&&this.$(f);this.$=this.g=null;this.g=this.H()}ha(f,k){f={adUnitId:d.bc(this.Wa,"rewarded"),npa:"NON_PERSONALIZED"===f?"1":"0"};this.D=!0;this.I=this.F=!1;this.g=null;this.g=this.H();this.u=new self.admob.RewardedAd(f);r.call(this,k);this.u.load()}async Ja(f){this.u?this.F?a(f,"rewarded ad already shown"):(this.D&&await this.H(),await (async()=>{this.I?(p.call(this,f),await this.u.show()):(r.call(this),this.I=!1,this.g=null,this.u.load(),
await this.H(),this.I?(p.call(this,f),await this.u.show()):b(f,"rewarded ad failed to load"))})()):b(f,"rewarded ad not created")}}function r(f){const k=()=>{this.D=!1;this.Ha(!0);f&&a(f,"rewarded ad load");document.removeEventListener(c.T,k);document.removeEventListener(c.U,g)},g=()=>{this.D=!1;this.Ha(!1);f&&b(f,"rewarded ad failed to load");document.removeEventListener(c.T,k);document.removeEventListener(c.U,g)};document.addEventListener(c.T,k);document.addEventListener(c.U,g)}function p(f){const k=
()=>{this.F=!0},g=u=>{this.ma=u.Rh},q=()=>{this.F=!1;f&&b(f,"rewarded ad failed to show");document.removeEventListener(c.ia,k);document.removeEventListener(c.ja,q);document.removeEventListener(c.Sa,g);document.removeEventListener(c.va,y)},y=()=>{if(null!==this.ma){const u=String(this.ma.type),w=String(this.ma.amount);f&&a(f,JSON.stringify([u,w]))}else f&&b(f,"closed with no reward");this.ma=null;this.F=!1;this.D=!0;this.I=!1;this.g=null;this.g=this.H();r.call(this);this.u.load();document.removeEventListener(c.ia,
k);document.removeEventListener(c.ja,q);document.removeEventListener(c.Sa,g);document.removeEventListener(c.va,y)};document.addEventListener(c.ia,k);document.addEventListener(c.ja,q);document.addEventListener(c.Sa,g);document.addEventListener(c.va,y)}self.jf=l}"use strict";
{const d=self.ab,a=d.ga,b=d.S,c={get T(){return self.admob.Events.rewardedInterstitialLoad},get U(){return self.admob.Events.rewardedInterstitialLoadFail},get ia(){return self.admob.Events.rewardedInterstitialShow},get ja(){return self.admob.Events.rewardedInterstitialShowFail},get va(){return self.admob.Events.rewardedInterstitialDismiss},get Sa(){return self.admob.Events.rewardedInterstitialReward}};class l{constructor(f,k){if(!f)return b(k,"Unit ID not specified");this.Wa=f;this.u=null;this.I=
this.F=this.D=!1;this.$=null;this.g=this.H();this.ma=null}H(){return this.g?this.g:this.g=new Promise(f=>{this.$=f})}Ha(f){this.I=f;this.$&&this.$(f);this.$=this.g=null;this.g=this.H()}ha(f,k){f={adUnitId:d.bc(this.Wa,"rewardedInterstitial"),npa:"NON_PERSONALIZED"===f?"1":"0"};this.D=!0;this.I=this.F=!1;this.g=null;this.g=this.H();this.u=new self.admob.RewardedInterstitialAd(f);r.call(this,k);this.u.load()}async Ja(f){this.u?this.F?a(f,"rewarded interstitial ad already shown"):(this.D&&await this.H(),
await (async()=>{this.I?(p.call(this,f),await this.u.show()):(r.call(this),this.I=!1,this.g=null,this.u.load(),await this.H(),this.I?(p.call(this,f),await this.u.show()):b(f,"rewarded interstitial ad failed to load"))})()):b(f,"rewarded interstitial ad not created")}}function r(f){const k=()=>{this.D=!1;this.Ha(!0);f&&a(f,"rewarded interstitial ad load");document.removeEventListener(c.T,k);document.removeEventListener(c.U,g)},g=()=>{this.D=!1;this.Ha(!1);f&&b(f,"rewarded interstitial ad failed to load");
document.removeEventListener(c.T,k);document.removeEventListener(c.U,g)};document.addEventListener(c.T,k);document.addEventListener(c.U,g)}function p(f){const k=()=>{this.F=!0},g=u=>{this.ma=u.Rh},q=()=>{this.F=!1;f&&b(f,"rewarded interstitial ad failed to show");document.removeEventListener(c.ia,k);document.removeEventListener(c.ja,q);document.removeEventListener(c.Sa,g);document.removeEventListener(c.va,y)},y=()=>{if(null!==this.ma){const u=String(this.ma.type),w=String(this.ma.amount);f&&a(f,JSON.stringify([u,
w]))}else f&&b(f,"closed with no reward");this.ma=null;this.F=!1;this.D=!0;this.I=!1;this.g=null;this.g=this.H();r.call(this);this.u.load();document.removeEventListener(c.ia,k);document.removeEventListener(c.ja,q);document.removeEventListener(c.Sa,g);document.removeEventListener(c.va,y)};document.addEventListener(c.ia,k);document.addEventListener(c.ja,q);document.addEventListener(c.Sa,g);document.addEventListener(c.va,y)}self.kf=l}"use strict";
{const d=self.ab,a=d.ga,b=d.S,c=self.cordova?"ios"===self.cordova.platformId:!1,l=self.cordova?"android"===self.cordova.platformId:!1,r=l?1:2,p=l?2:1;class f{constructor(){this.xa="UNKNOWN";this.ya="";this.Gb=0;this.kb="UNKNOWN";this.sa="not-determined";this.Cd=!1}async Yc(){d.Pa.debug&&await self.consent.reset()}async ce(){c&&await self.admob.requestTrackingAuthorization()}async ec(){if(l)return this.sa="not-determined";const A=self.cordova.plugins.idfa,B=await A.Jh();if(!B.Wh)return this.sa="authorized";
switch(B.pi){case A.ei:return this.sa="not-determined";case A.fi:return this.sa="denied";case A.di:return this.sa="denied";case A.ci:return this.sa="authorized"}}async Hf(A){l?a(A,"not-determined"):c&&(await u.call(this),"true"===this.ya?await this.ce():(await this.ec(),"not-determined"===this.sa&&(await k.call(this),this.Cd?await this.Of():await this.ce())),await this.ec(),a(A,this.sa))}async If(A,B,F){return await x.call(this,A,B,h=>{h?b(F,h.message):b(F,"requestInfoUpdate error")})}async Jf(A,
B){await x.call(this,A,B)}async bd(A,B=!1){await g.call(this);switch(A){case "eu":B=await k.call(this);q.call(this)&&B&&await (await self.consent.loadForm()).show();break;case "always":{A=await k.call(this);const F=await u.call(this);A&&"true"===F?await (await self.consent.loadForm()).show():A&&B&&await (await self.consent.loadForm()).show()}}await g.call(this);await u.call(this);await y.call(this)}async Of(){await this.bd("always",!0)}async ge(){await g.call(this);await u.call(this);await y.call(this)}async Qf(A){await this.ec();
a(A,`${this.kb}&&${this.sa}&&${this.ya}`)}async Pf(A){await this.ge();await this.ec();a(A,`${this.kb}&&${this.sa}&&${this.ya}`)}}async function k(){return this.Cd=await self.consent.getFormStatus()===self.consent.FormStatus.Available}async function g(){this.Gb=await self.consent.getConsentStatus();switch(this.Gb){case p:return this.kb="REQUIRED";case r:return this.kb="NOT_REQUIRED";case 3:return this.kb="OBTAINED";case 0:return this.kb="UNKNOWN"}}function q(){switch(this.Gb){case p:return!0;case r:return!1;
case 3:return!1;case 0:return!0}}function y(){switch(this.Gb){case p:return this.xa="NON_PERSONALIZED";case r:return this.xa="PERSONALIZED";case 3:return this.xa="PERSONALIZED";case 0:return this.xa="NON_PERSONALIZED"}}async function u(){if(l)switch(this.Gb){case p:return this.ya="true";case r:return this.ya="false";case 3:return this.ya="true";case 0:return this.ya="true"}if(c)return await w.call(this,"IABTCF_gdprApplies","getInt")?this.ya="true":this.ya="false"}async function w(A,B){return new Promise(F=>
{self.NativeStorage[B](A,h=>F(h),()=>F(1))})}async function x(A,B,F){let h="",m=null;if(A){switch(B){case "EEA":h=self.consent.DebugGeography.EEA;break;case "NOT_EEA":h=self.consent.DebugGeography.NotEEA;break;default:h=self.consent.DebugGeography.Disabled}m=[await d.Rf]}try{return A?await self.consent.requestInfoUpdate({ii:h,oi:m}):await self.consent.requestInfoUpdate(),!0}catch(e){return F&&F(e),!1}}self.ef=new f}"use strict";
{const d=(r,p)=>{let f=r[0],k=r[1],g=r[2],q=r[3];f=a(k&g|~k&q,f,k,p[0],7,-680876936);q=a(f&k|~f&g,q,f,p[1],12,-389564586);g=a(q&f|~q&k,g,q,p[2],17,606105819);k=a(g&q|~g&f,k,g,p[3],22,-1044525330);f=a(k&g|~k&q,f,k,p[4],7,-176418897);q=a(f&k|~f&g,q,f,p[5],12,1200080426);g=a(q&f|~q&k,g,q,p[6],17,-1473231341);k=a(g&q|~g&f,k,g,p[7],22,-45705983);f=a(k&g|~k&q,f,k,p[8],7,1770035416);q=a(f&k|~f&g,q,f,p[9],12,-1958414417);g=a(q&f|~q&k,g,q,p[10],17,-42063);k=a(g&q|~g&f,k,g,p[11],22,-1990404162);f=a(k&g|~k&
q,f,k,p[12],7,1804603682);q=a(f&k|~f&g,q,f,p[13],12,-40341101);g=a(q&f|~q&k,g,q,p[14],17,-1502002290);k=a(g&q|~g&f,k,g,p[15],22,1236535329);f=a(k&q|g&~q,f,k,p[1],5,-165796510);q=a(f&g|k&~g,q,f,p[6],9,-1069501632);g=a(q&k|f&~k,g,q,p[11],14,643717713);k=a(g&f|q&~f,k,g,p[0],20,-373897302);f=a(k&q|g&~q,f,k,p[5],5,-701558691);q=a(f&g|k&~g,q,f,p[10],9,38016083);g=a(q&k|f&~k,g,q,p[15],14,-660478335);k=a(g&f|q&~f,k,g,p[4],20,-405537848);f=a(k&q|g&~q,f,k,p[9],5,568446438);q=a(f&g|k&~g,q,f,p[14],9,-1019803690);
g=a(q&k|f&~k,g,q,p[3],14,-187363961);k=a(g&f|q&~f,k,g,p[8],20,1163531501);f=a(k&q|g&~q,f,k,p[13],5,-1444681467);q=a(f&g|k&~g,q,f,p[2],9,-51403784);g=a(q&k|f&~k,g,q,p[7],14,1735328473);k=a(g&f|q&~f,k,g,p[12],20,-1926607734);f=a(k^g^q,f,k,p[5],4,-378558);q=a(f^k^g,q,f,p[8],11,-2022574463);g=a(q^f^k,g,q,p[11],16,1839030562);k=a(g^q^f,k,g,p[14],23,-35309556);f=a(k^g^q,f,k,p[1],4,-1530992060);q=a(f^k^g,q,f,p[4],11,1272893353);g=a(q^f^k,g,q,p[7],16,-155497632);k=a(g^q^f,k,g,p[10],23,-1094730640);f=a(k^
g^q,f,k,p[13],4,681279174);q=a(f^k^g,q,f,p[0],11,-358537222);g=a(q^f^k,g,q,p[3],16,-722521979);k=a(g^q^f,k,g,p[6],23,76029189);f=a(k^g^q,f,k,p[9],4,-640364487);q=a(f^k^g,q,f,p[12],11,-421815835);g=a(q^f^k,g,q,p[15],16,530742520);k=a(g^q^f,k,g,p[2],23,-995338651);f=a(g^(k|~q),f,k,p[0],6,-198630844);q=a(k^(f|~g),q,f,p[7],10,1126891415);g=a(f^(q|~k),g,q,p[14],15,-1416354905);k=a(q^(g|~f),k,g,p[5],21,-57434055);f=a(g^(k|~q),f,k,p[12],6,1700485571);q=a(k^(f|~g),q,f,p[3],10,-1894986606);g=a(f^(q|~k),g,
q,p[10],15,-1051523);k=a(q^(g|~f),k,g,p[1],21,-2054922799);f=a(g^(k|~q),f,k,p[8],6,1873313359);q=a(k^(f|~g),q,f,p[15],10,-30611744);g=a(f^(q|~k),g,q,p[6],15,-1560198380);k=a(q^(g|~f),k,g,p[13],21,1309151649);f=a(g^(k|~q),f,k,p[4],6,-145523070);q=a(k^(f|~g),q,f,p[11],10,-1120210379);g=a(f^(q|~k),g,q,p[2],15,718787259);k=a(q^(g|~f),k,g,p[9],21,-343485551);r[0]=f+r[0]&4294967295;r[1]=k+r[1]&4294967295;r[2]=g+r[2]&4294967295;r[3]=q+r[3]&4294967295},a=(r,p,f,k,g,q)=>{p=(p+r&4294967295)+(k+q&4294967295)&
4294967295;return(p<<g|p>>>32-g)+f&4294967295},b=r=>{const p=r.length,f=[1732584193,-271733879,-1732584194,271733878];let k;for(k=64;k<=r.length;k+=64){{var g=r.substring(k-64,k);const q=[];for(let y=0;64>y;y+=4)q[y>>2]=g.charCodeAt(y)+(g.charCodeAt(y+1)<<8)+(g.charCodeAt(y+2)<<16)+(g.charCodeAt(y+3)<<24);g=q}d(f,g)}r=r.substring(k-64);g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(k=0;k<r.length;k++)g[k>>2]|=r.charCodeAt(k)<<(k%4<<3);g[k>>2]|=128<<(k%4<<3);if(55<k)for(d(f,g),k=0;16>k;k++)g[k]=0;g[14]=8*
p;d(f,g);return f},c="0123456789abcdef".split(""),l=r=>{for(let k=0;k<r.length;k++){var p=k;{var f=r[k];let g="";for(let q=0;4>q;q++)g+=c[f>>8*q+4&15]+c[f>>8*q&15];f=g}r[p]=f}return r.join("")};l(b("hello"));self.Td=r=>l(b(r))}"use strict";
{const d=self.ab,a=self.ef,b=self.df,c=self.hf,l=self.jf,r=self.kf;let p=null,f=null,k=null,g=null,q=null;const y={CreateBannerAdvert:async(u,w,x,A,B)=>{await d.la(B,x)&&(x=await a.xa,p||(p=new b(u,w,A,B)),p.ha(x,B))},ShowBannerAdvert:async u=>{if(!p)return d.S(u,"banner ad not created");p.Ja(u)},HideBannerAdvert:async u=>{if(!p)return d.S(u,"banner ad not created");p.wf(u)},CreateInterstitialAdvert:async(u,w,x)=>{if(f)return d.ga(x,"interstitial ad already created");await d.la(x,w)&&(w=await a.xa,
f=new c(u,x),f.ha(w,x))},ShowInterstitialAdvert:async u=>{if(!f)return d.S(u,"interstitial ad not created");f.Ja(u)},CreateVideoAdvert:async(u,w,x)=>{if(k||g)return d.ga(x,"video ad already created");await d.la(x,w)&&(w=await a.xa,k=new l(u,x),k.ha(w,x))},ShowVideoAdvert:async u=>{if(!k)return d.S(u,"video ad not created");k.Ja(u)},CreateRewardedAdvert:async(u,w,x)=>{if(g||k)return d.ga(x,"rewarded ad already created");await d.la(x,w)&&(w=await a.xa,g=new l(u,x),g.ha(w,x))},ShowRewardedAdvert:async u=>
{if(!g)return d.S(u,"rewarded ad not created");g.Ja(u)},CreateRewardedInterstitialAdvert:async(u,w,x)=>{if(q)return d.ga(x,"rewarded interstitial ad already created");await d.la(x,w)&&(w=await a.xa,q=new r(u,x),q.ha(w,x))},ShowRewardedInterstitialAdvert:async u=>{if(!q)return d.S(u,"rewarded interstitial ad not created");q.Ja(u)},Configure:async(u,w,x,A,B,F,h,m,e)=>{const n=!d.vf();d.Kf(u,w,x,A,B,F,h);await d.la(e,F)&&(n&&await a.Yc(),await a.If(F,h,e)&&(n?m?await a.bd("eu"):await a.ge():await a.bd("always"),
await a.Qf(e)))},RequestConsent:async u=>{y.Configure(d.Pa.id,d.Pa.Ph,d.Pa.Nh,d.Pa.Th,"always",d.Pa.debug,d.Pa.Gh,!1,u)},SetMaxAdContentRating:async(u,w)=>{if(await d.la(w)){if(!u)return d.S(w,"Label not specified");try{d.dd("maxAdContentRating",u),d.ga(w,"")}catch(x){d.S(w,"invalid label")}}},TagForChildDirectedTreatment:async(u,w)=>{if(await d.la(w))try{d.dd("tagForChildDirectedTreatment",1===u?!0:!1),d.ga(w,"")}catch(x){d.S(w,"invalid label")}},TagForUnderAgeOfConsent:async(u,w)=>{if(await d.la(w))try{d.dd("tagForUnderAgeOfConsent",
1===u?!0:!1),d.ga(w,"")}catch(x){d.S(w,"invalid label")}},RequestIDFA:async u=>{await d.la(u)&&a.Hf(u)},StatusUpdate:async(u,w,x)=>{await d.la(x,u)&&(await a.Jf(u,w),await a.Pf(x))}};self.bb||(self.bb={});self.bb.Qh=y}"use strict";
{const d={},a=(g,q)=>d[g]=q,b=g=>new Promise(q=>setTimeout(q,g));let c=null,l=null,r=null,p=null,f=null;function k(g,q){const y=q.slice(0,-1);q=q[q.length-1];console.log(g,y);return[y,q]}a("CreateBannerAdvert",async(...g)=>{[,g]=k("CreateBannerAdvert",g);await b(50);c?g("Banner already exists"):(c="ready",g(null,"Created banner"))});a("ShowBannerAdvert",async(...g)=>{[,g]=k("ShowBannerAdvert",g);await b(50);"ready"!=c?g("Banner cannot be shown"):(c="shown",g(null,"Showed banner"))});a("HideBannerAdvert",
async(...g)=>{[,g]=k("HideBannerAdvert",g);await b(50);"shown"!=c?g("Banner cannot be hidden"):(c=null,g(null,"Hid banner"))});a("CreateInterstitialAdvert",async(...g)=>{[,g]=k("CreateInterstitialAdvert",g);await b(50);l?g("Intersitial already exists"):(l="ready",g(null,"Created interstitial"))});a("ShowInterstitialAdvert",async(...g)=>{[,g]=k("ShowInterstitialAdvert",g);await b(50);"ready"!=l?g("Cannot show interstitial"):(l=null,g(null,"Interstitial shown"))});a("CreateVideoAdvert",async(...g)=>
{[,g]=k("CreateVideoAdvert",g);await b(50);r?g("Video already exists"):(r="ready",g(null,"Created video"))});a("ShowVideoAdvert",async(...g)=>{[,g]=k("ShowVideoAdvert",g);await b(50);"ready"!=r?g("Cannot show video"):(r=null,g(null,'["example type", 20]'))});a("CreateRewardedAdvert",async(...g)=>{[,g]=k("CreateRewardedAdvert",g);await b(50);p?g("Rewarded already exists"):(p="ready",g(null,"Created rewarded"))});a("ShowRewardedAdvert",async(...g)=>{[,g]=k("ShowRewardedAdvert",g);await b(50);"ready"!=
p?g("Cannot show rewarded"):(p=null,g(null,'["example type", 20]'))});a("CreateRewardedInterstitialAdvert",async(...g)=>{[,g]=k("CreateRewardedInterstitialAdvert",g);await b(50);f?g("Rewarded intersitial already exists"):(f="ready",g(null,"Created rewarded interstitial"))});a("ShowRewardedInterstitialAdvert",async(...g)=>{[,g]=k("ShowRewardedInterstitialAdvert",g);await b(50);"ready"!=f?g("Cannot show rewarded interstitial"):(f=null,g(null,"Rewarded interstitial shown"))});a("Configure",async(...g)=>
{[,g]=k("Configure",g);await b(50);g(null,"PERSONALIZED&&true")});a("RequestConsent",async(...g)=>{[,g]=k("RequestConsent",g);await b(50);g(null,"PERSONALIZED&&true")});a("RequestIDFA",async(...g)=>{[,g]=k("RequestIDFA",g);await b(50);g(null,"authorized")});self.bb||(self.bb={});self.bb.ji=d}"use strict";
{let d=!1;self.Ia.wb(class extends self.cb{constructor(a){super(a,"advert");a=b=>[b,c=>this.Zf(b,c)];K(this,[a("CreateBannerAdvert"),a("ShowBannerAdvert"),a("HideBannerAdvert"),a("CreateInterstitialAdvert"),a("ShowInterstitialAdvert"),a("CreateVideoAdvert"),a("ShowVideoAdvert"),a("CreateRewardedAdvert"),a("ShowRewardedAdvert"),a("CreateRewardedInterstitialAdvert"),a("ShowRewardedInterstitialAdvert"),a("Configure"),a("RequestConsent"),a("SetUserPersonalisation"),a("SetMaxAdContentRating"),a("TagForChildDirectedTreatment"),
a("TagForUnderAgeOfConsent"),a("RequestIDFA"),a("StatusUpdate")])}async Zf(a,b){let c;self.cordova&&(c=self.bb.Qh);if(!c)throw d||(d=!0,console.warn("The Mobile Advert plugin is not loaded. Please note that it only works in Android or iOS exports")),Error("advert plugin not loaded");return new Promise((l,r)=>{(0,c[a])(...b,(p,f)=>{p?r(p):l(f)})})}})};
